[package]
name = "bishop"
version = "0.1.0"
authors = ["Stefan Radziuk <stefan.radziuk19@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
